# Generated by Django 5.2.3 on 2025-06-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя, полученное со страницы списка', max_length=255)),
                ('link', models.URLField(help_text='Ссылка на профиль на barreaulyon.com', unique=True)),
                ('status', models.CharField(default='New', help_text='Статус обработки записи', max_length=20)),
                ('full_name_title', models.CharField(blank=True, help_text='Maître ...', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('structure', models.CharField(blank=True, help_text='Название структуры или кабинета', max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('case_number', models.CharField(blank=True, help_text='Case', max_length=100, null=True)),
                ('oath_date', models.CharField(blank=True, help_text='Дата присяги', max_length=100, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('specializations', models.TextField(blank=True, help_text='Упомянутые специализации', null=True)),
                ('activity_areas', models.TextField(blank=True, help_text='Сферы деятельности', null=True)),
            ],
        ),
    ]
